###############################################
# Common Keys for all apps
###############################################

x-common-keys: &common-keys
  env_file: ".env"
  restart: unless-stopped
  logging:
    driver: json-file
  environment:
    PUID: 1000
    PGID: 1000
    TZ: Australia/Adelaide
  dns:
    - 1.1.1.1
    - 1.0.0.1
x-common-healthcheck: &common-healthcheck
  interval: 30s
  timeout: 5s
  retries: 3
  start_period: 30s

services:
  ###############################################
  # RADARR - Movies
  ###############################################
  radarr:
    <<: *common-keys
    container_name: radarr
    image: ghcr.io/hotio/radarr:latest
    ports:
      - 7878:7878
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/appdata/radarr:/config
      - /home/butler/data:/data
    healthcheck:
      <<: *common-healthcheck
      test: ["CMD-SHELL", "curl -f http://localhost:7878 || exit 1"]



  ###############################################
  # SONARR - TV Shows
  ###############################################

  sonarr:
    <<: *common-keys
    container_name: sonarr
    image: ghcr.io/hotio/sonarr:latest
    ports:
      - 8989:8989
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/appdata/sonarr:/config
      - /home/butler/data:/data
    healthcheck:
      <<: *common-healthcheck
      test: ["CMD-SHELL", "curl -f http://localhost:8989/ping || exit 1"]

  ###############################################
  # BAZARR - Subtitles
  ###############################################

  bazarr:
    <<: *common-keys
    container_name: bazarr
    image: ghcr.io/hotio/bazarr:latest
    ports:
      - 6767:6767
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/appdata/bazarr:/config
      - /home/butler/data/media:/data/media
    healthcheck:
      <<: *common-healthcheck
      test: ["CMD-SHELL", "curl -f http://localhost:6767/api/system/status?apikey=${BAZARR_API_KEY}  || exit 1"]

  ###############################################
  # PROWLARR - Indexer Manager
  ###############################################

  prowlarr:
    <<: *common-keys
    container_name: prowlarr
    image: ghcr.io/hotio/prowlarr:latest
    ports:
      - 9696:9696
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/appdata/prowlarr:/config
    healthcheck:
      <<: *common-healthcheck
      test: ["CMD-SHELL", "curl -f http://localhost:9696/ping || exit 1"]

  ###############################################
  # QBITTORRENT - Downloader
  ###############################################

  qbittorrent:
    <<: *common-keys
    container_name: qbittorrent
    image: ghcr.io/hotio/qbittorrent:latest
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    environment:
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/appdata/qbittorrent:/config
      - /home/butler/data:/data
    healthcheck:
      <<: *common-healthcheck
      test: ["CMD-SHELL", "curl -fsS -c /tmp/qb.cookie -d \"username=${Q_USERNAME}\" -d \"password=${Q_PASSWORD}\" http://localhost:8080/api/v2/auth/login >/dev/null && curl -fsS -b /tmp/qb.cookie http://localhost:8080/api/v2/app/webapiVersion >/dev/null"]

  ###############################################
  # JELLYFIN - Media Server
  ###############################################

  jellyfin:
    <<: *common-keys
    container_name: jellyfin
    image: ghcr.io/hotio/jellyfin:latest
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/appdata/jellyfin:/config
      - /home/butler/data/media:/data/media
    ports:
      - 8096:8096
    healthcheck:
      <<: *common-healthcheck
      test: ["CMD-SHELL", "curl -f http://localhost:8096/health || exit 1"]

  ###############################################
  # JELLYSEER - Media Request Library
  ###############################################

  jellyseerr:
    <<: *common-keys
    container_name: jellyseerr
    image: fallenbagel/jellyseerr:latest
    environment:
         - LOG_LEVEL=debug
    ports:
         - 5055:5055
    volumes:
         - /path/to/appdata/config:/app/config
    restart: unless-stopped
    healthcheck:
      <<: *common-healthcheck
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:5055/api/v1/status || exit 1"]

####################################################
# FLARESOLVERR - Cloudflare Bypass
####################################################

  flaresolverr:
    <<: *common-keys
    container_name: flaresolverr
    image: ghcr.io/flaresolverr/flaresolverr:latest
    ports:
      - 8191:8191
    environment:
      - LOG_LEVEL=info
    healthcheck:
      <<: *common-healthcheck
      test: ["CMD-SHELL", "curl -fs http://localhost:8191/ | grep -q 'FlareSolverr is ready!' || exit 1"]

###############################################
# ARR Stack Dedicated Network
###############################################

networks:
  default:
    name: arr_network

###############################################
###############################################
