# Portainer
services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    dns:
      - 8.8.8.8
      - 1.1.1.1
    ports:
      - "9443:9443"
#      - "8000:8000" Only required if using a TCP tunnel Server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

volumes:
  portainer_data:
    external: true
