#Cloudflared Tunnel
services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared-tunnel
    env_file: ".env"
    dns:
      - 1.1.1.1
      - 9.9.9.9
    restart: always
    environment:
      - TUNNEL_METRICS=0.0.0.0:60123
    command: tunnel --no-autoupdate run --token "${TUNNEL_TOKEN}"
    healthcheck:
      test: ['CMD', 'cloudflared', 'tunnel', 'ready']
      interval: 1s
      timeout: 2s
      retries: 60
