#Cloudflared Tunnel
services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared-tunnel
    env_file: ".env"
    dns:
      - 1.1.1.1
      - 9.9.9.9
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token "${TUNNEL_TOKEN}"
